# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  name: NewPool  # or your custom pool name

steps:
- script: echo "Agent is working!"
  displayName: 'Test Agent Run'
